set(SUPER_SCORPIO_URL_BASE "https://github.com/steffenyount/super-scorpio/tree")
macro(auto_set_url TARGET)
    file(RELATIVE_PATH URL_REL_PATH "${SUPER_SCORPIO_PATH}" "${CMAKE_CURRENT_LIST_DIR}")
    pico_set_program_url(${TARGET} "${SUPER_SCORPIO_URL_BASE}/${URL_REL_PATH}")
endmacro()
